
'use server';
/**
 * @fileOverview A flow to enhance or modify images using Gemini.
 */

import { ai } from '@/ai/genkit';
import { googleAI } from '@genkit-ai/google-genai';
import { z } from 'genkit';

const EnhanceImageInputSchema = z.object({
  photoDataUri: z.string().describe("The original image as a data URI."),
  prompt: z.string().describe("Instructions for enhancement (e.g., 'increase contrast', 'remove background')."),
});

const EnhanceImageOutputSchema = z.object({
  enhancedPhotoDataUri: z.string().describe("The generated/enhanced image as a data URI."),
});

// Use stable identifier for image tasks
const MODEL_ID = 'gemini-1.5-flash-latest';

export async function enhanceImage(input: z.infer<typeof EnhanceImageInputSchema>) {
  return enhanceImageFlow(input);
}

const enhanceImageFlow = ai.defineFlow(
  {
    name: 'enhanceImageFlow',
    inputSchema: EnhanceImageInputSchema,
    outputSchema: EnhanceImageOutputSchema,
  },
  async (input) => {
    const { media } = await ai.generate({
      model: googleAI.model(MODEL_ID),
      prompt: [
        { media: { url: input.photoDataUri } },
        { text: `Enhance this image according to these instructions: ${input.prompt}. Return only the modified image.` },
      ],
      config: {
        responseModalities: ['IMAGE'],
      },
    });

    if (!media) {
      throw new Error('No image was generated by the model.');
    }

    return {
      enhancedPhotoDataUri: media.url,
    };
  }
);
